name: growfast-website
services:
  app:
    image:
      context: .
      dockerfile: ./Dockerfile.easypanel
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://neondb_owner:npg_EvMIlCrL47Yx@ep-little-voice-aeekmg7d-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - SESSION_SECRET=$(SESSION_SECRET)
      - CLERK_PUBLISHABLE_KEY=$(CLERK_PUBLISHABLE_KEY)
      - CLERK_SECRET_KEY=$(CLERK_SECRET_KEY)
      - SMTP_HOST=$(SMTP_HOST)
      - SMTP_PORT=$(SMTP_PORT)
      - SMTP_SECURE=$(SMTP_SECURE)
      - SMTP_USER=$(SMTP_USER)
      - SMTP_PASS=$(SMTP_PASS)
      - FRONTEND_URL=https://$(PRIMARY_DOMAIN)
      - PGHOST=ep-little-voice-aeekmg7d-pooler.c-2.us-east-2.aws.neon.tech
      - PGPORT=5432
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_EvMIlCrL47Yx
      - PGDATABASE=neondb
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1G

    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_logs: 