[build]
  publish = "dist/public"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_API_BASE/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

