[build]
  base = "web"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Set NEXT_PUBLIC_API_BASE_URL in Netlify UI to your API domain
# No redirects are needed if your frontend calls the API via NEXT_PUBLIC_API_BASE_URL

